### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by BluePixel4k** [soupslurpr/platform_packages_apps_NetworkLocation#1]
Hi @soupslurpr,
is it already possible to pre-test this app/feature inside GrapheneOS?

It is already possible to estimate when we will see an official integration into GrapheneOS?

Thank you! :)

**Comment by soupslurpr** [comment]
Hi, thanks for your interest. At this time testing isn't needed. When the feature is ready and gone through internal testing, you'll be able to test it out in an official OS release as it gets pushed through alpha, then beta, then finally stable if there aren't any major issues.

**Comment by soupslurpr** [comment]
lookout for the next OS release :D

this repo has been deleted so I can fork the GrapheneOS org one
